### ISSUE TITLE
trouble with Adafruit FT232H

### ISSUE THREAD

**Issue by LwServices** [vicmatmar/FTD2XX_NET#1]
Hello I have Try to use this libary and
i get alwayas an error with FT_CreateDeviceInfoList

now i have found:
By default, the driver will support a limited set of VID and PID matched devices (VID 0x0403 with PIDs 0x6001, 0x6010, 0x6006 only).
In order to use the driver with other VID and PID combinations the FT_SetVIDPID function must be used prior to calling FT_ListDevices, FT_Open, FT_OpenEx or FT_CreateDeviceInfoList.

My device is 0x403,0x6014
so now i have to use the FT_SetVIDPID function 

i have no idea how to do this

is it implemented? how to call it?

thank you in advance

Leszek

**Comment by vicmatmar** [comment]
I'm looking at the programming guide at:

https://www.us.tdk-lambda.com/HP/pdfs/Product_manuals/USB%20D2XX%20Programmer's%20Guide.pdf

3.1 FT_SetVIDPID
Supported Operating Systems
Linux
Mac OS X (10.4 and later)


This is a .net lib intended for windows.  In any case, this lib just wraps all the functions from the D2XX driver.  You may try to and look how all the other functions are done in the FTD2XX_NET/FTDI.cs file and add the wrapper for that function:

FT_STATUS FT_SetVIDPID (DWORD dwVID, DWORD dwPID)

**Comment by LwServices** [comment]
thank you for this information
but so far i decided to use an nusbio interface
